version: '3.8'

# 1
services:
  postgres1:
    image: postgres
    container_name: postgres1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
  
  # 2
  postgres2:
    image: postgres
    container_name: postgres2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: database2
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
  
  # 3
  postgres3:
    image: postgres
    container_name: postgres3
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: database3
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3

  #   # 4

  # postgres4:
  #   image: postgres
  #   container_name: postgres4
  #   ports:
  #     - "5435:5432"
  #   environment:
  #     POSTGRES_DB: database4
  #     POSTGRES_USER: user4
  #     POSTGRES_PASSWORD: password4

  #   # 5
  #   postgres5:
  #   image: postgres
  #   container_name: postgres5
  #   ports:
  #     - "5436:5432"
  #   environment:
  #     POSTGRES_DB: database5
  #     POSTGRES_USER: user5
  #     POSTGRES_PASSWORD: password5

  #   # 6
  #   postgres6:
  #   image: postgres
  #   container_name: postgres6
  #   ports:
  #     - "5437:5432"
  #   environment:
  #     POSTGRES_DB: database6
  #     POSTGRES_USER: user6
  #     POSTGRES_PASSWORD: password6

  #   # 7
  #   postgres7:
  #   image: postgres
  #   container_name: postgres7
  #   ports:
  #     - "5438:5432"
  #   environment:
  #     POSTGRES_DB: database7
  #     POSTGRES_USER: user7
  #     POSTGRES_PASSWORD: password7


  #   # 8
  #   postgres8:
  #   image: postgres
  #   container_name: postgres8
  #   ports:
  #     - "5439:5432"
  #   environment:
  #     POSTGRES_DB: database8
  #     POSTGRES_USER: user8
  #     POSTGRES_PASSWORD: password8

